### PR TITLE
Check QR version

### PR DESCRIPTION
**Pull request by christianpaquin**
QR codes shouldn't exceed version 22 (with 105x105 modules), provide a warning if they do. Fixes issue #56.

 - [x] implement QR version check
 - [x] add test for QR version

### CODE REVIEW

**Comment by christianpaquin** [comment]
Our current QR scanning lib doesn't return the version/module info, so we'll need an alternative way of doing this.

**Comment by christianpaquin** [comment]
The easiest way to get the version back is to have jsQR return it. I [opened a PR](https://github.com/cozmo/jsQR/pull/202) on the project; let's see if it gets through rapidly. Otherwise, we'll need to find an alternative solution.

**Comment by christianpaquin** [comment]
The PR mentioned above was merged in jsQR. Updating to v1.4.0 will allow us to get the QR version back.

**Comment by christianpaquin** [comment]
Ran `npm update` to get latest jsQR version, allowing to read the QR version.

**Review by ljoy913 — APPROVED** [review]

**Pull request merged**
